Repository AY2223S1-CS2103-W14-1/tp, pull requests merged in 2022-11, with the labels that each got.

#205 Fix documentation
  docs/UserGuide.md
Labels: type.Documentation

#204 update userguide
  docs/UserGuide.md
Labels: priority.Low, severity.Low, type.Documentation

#202 add clearer explanations for options
  docs/UserGuide.md
Labels: type.Bug, type.Documentation

#212 Fix tag
  src/main/java/seedu/condonery/model/property/Property.java
Labels: type.Bug

#217 Fixes for UG (Check commits for each specific fix)
  docs/UserGuide.md
Labels: priority.Medium, severity.Low, type.Documentation

#214 Update developer guide for range command
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/RangeActivityDiagram.puml
  docs/diagrams/RangeExecuteSequenceDiagram.puml
  docs/diagrams/RangeSequenceDiagram.puml
  docs/images/RangeActivityDiagram.png
  docs/images/RangeExecuteSequenceDiagram.png
  docs/images/RangeSequenceDiagram.png
  docs/team/zacchaeuschok.md
  src/main/java/seedu/condonery/logic/parser/CondoneryParser.java
Labels: type.Documentation

#208 Modify documentation for Type and Status property commands
  docs/UserGuide.md
  src/main/java/seedu/condonery/logic/parser/property/StatusPropertyCommandParser.java
  src/main/java/seedu/condonery/logic/parser/property/TypePropertyCommandParser.java
Labels: type.Documentation

#229 Add implementation for StatusPropertyCommand in Developer Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/StatusPropertyActivityDiagram.png
  docs/diagrams/StatusPropertyActivityDiagram.puml
  docs/diagrams/StatusPropertySequenceDiagram.puml
  docs/images/StatusPropertyActivityDiagram.png
  docs/images/StatusPropertySequenceDiagram.png
Labels: type.Documentation

#239 Fix UG errors
  docs/UserGuide.md
Labels: type.Documentation

#264 Fix errors in Manual Testing instructions
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/images/yuehernkang.png
  docs/team/yuehernkang.md
Labels: type.Documentation
