Repository AY2223S1-CS2103-W14-1/tp, pull requests merged in 2022-10, with the labels that each got.

#23 Update user profile and user stories in Developer Guide
  docs/DeveloperGuide.md
Labels: type.Task

#48 Modify property list command
  src/test/java/seedu/condonery/logic/LogicManagerTest.java
  src/test/java/seedu/condonery/logic/commands/AddCommandTest.java
  src/test/java/seedu/condonery/logic/commands/CommandTestUtil.java
  src/test/java/seedu/condonery/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/condonery/logic/commands/EditCommandTest.java
  src/test/java/seedu/condonery/logic/commands/FindCommandTest.java
  src/test/java/seedu/condonery/model/ModelManagerTest.java
  src/test/java/seedu/condonery/testutil/TestUtil.java
Labels: type.Story

#52 Fix Unit Tests
  src/test/java/seedu/condonery/logic/LogicManagerTest.java
  src/test/java/seedu/condonery/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/condonery/logic/commands/AddCommandTest.java
  src/test/java/seedu/condonery/logic/commands/ClearCommandTest.java
  src/test/java/seedu/condonery/logic/commands/CommandTestUtil.java
  src/test/java/seedu/condonery/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/condonery/logic/commands/EditCommandTest.java
  src/test/java/seedu/condonery/logic/commands/EditPropertyDescriptorTest.java
  src/test/java/seedu/condonery/logic/commands/ExitCommandTest.java
  src/test/java/seedu/condonery/logic/commands/FindCommandTest.java
  src/test/java/seedu/condonery/logic/commands/HelpCommandTest.java
  src/test/java/seedu/condonery/logic/commands/ListCommandTest.java
  src/test/java/seedu/condonery/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/condonery/logic/parser/CondoneryParserTest.java
  src/test/java/seedu/condonery/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/condonery/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/condonery/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/condonery/logic/parser/ParserUtilTest.java
  src/test/java/seedu/condonery/model/ModelManagerTest.java
  src/test/java/seedu/condonery/model/PropertyDirectoryTest.java
  src/test/java/seedu/condonery/storage/JsonPropertyDirectoryStorageTest.java
  src/test/java/seedu/condonery/storage/JsonSerializablePropertyDirectoryTest.java
  src/test/java/seedu/condonery/storage/StorageManagerTest.java
  src/test/java/seedu/condonery/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/condonery/testutil/EditPropertyDescriptorBuilder.java
  src/test/java/seedu/condonery/testutil/PropertyBuilder.java
  src/test/java/seedu/condonery/testutil/PropertyDirectoryBuilder.java
  src/test/java/seedu/condonery/testutil/PropertyUtil.java
  src/test/java/seedu/condonery/testutil/TestUtil.java
  src/test/java/seedu/condonery/testutil/TypicalIndexes.java
  src/test/java/seedu/condonery/testutil/TypicalPersons.java
  src/test/java/seedu/condonery/testutil/TypicalProperties.java
Labels: priority.High

#57 Modify the add command to take in a -p argument
  src/main/java/seedu/condonery/logic/commands/property/.AddPropertyCommand.java.swp
  src/main/java/seedu/condonery/logic/commands/property/AddPropertyCommand.java
  src/main/java/seedu/condonery/logic/parser/CondoneryParser.java
  src/main/java/seedu/condonery/logic/parser/property/AddPropertyCommandParser.java
Labels: type.Story

#53 Add filter command
  docs/AboutUs.md
  docs/UserGuide.md
  src/main/java/seedu/condonery/commons/util/StringUtil.java
  src/main/java/seedu/condonery/logic/commands/property/FilterPropertyCommand.java
  src/main/java/seedu/condonery/logic/parser/CondoneryParser.java
  src/main/java/seedu/condonery/logic/parser/property/FilterPropertyCommandParser.java
  src/main/java/seedu/condonery/model/property/Property.java
  src/main/java/seedu/condonery/model/property/TagContainsKeywordsPredicate.java
Labels: type.Story, priority.High

#88 Add price range command
  docs/DeveloperGuide.md
  src/main/java/seedu/condonery/logic/commands/client/EditClientCommand.java
  src/main/java/seedu/condonery/logic/commands/property/AddPropertyCommand.java
  src/main/java/seedu/condonery/logic/commands/property/EditPropertyCommand.java
  src/main/java/seedu/condonery/logic/commands/property/RangePropertyCommand.java
  src/main/java/seedu/condonery/logic/parser/CliSyntax.java
  src/main/java/seedu/condonery/logic/parser/CondoneryParser.java
  src/main/java/seedu/condonery/logic/parser/ParserUtil.java
  src/main/java/seedu/condonery/logic/parser/property/AddPropertyCommandParser.java
  src/main/java/seedu/condonery/logic/parser/property/EditPropertyCommandParser.java
  src/main/java/seedu/condonery/logic/parser/property/RangePropertyCommandParser.java
  src/main/java/seedu/condonery/model/property/Price.java
  src/main/java/seedu/condonery/model/property/Property.java
  src/main/java/seedu/condonery/model/property/PropertyPriceWithinRangePredicate.java
  src/main/java/seedu/condonery/model/util/SampleDataUtil.java
  src/main/java/seedu/condonery/storage/JsonAdaptedProperty.java
  src/main/java/seedu/condonery/ui/PropertyCard.java
  src/main/resources/view/PropertyListCard.fxml
  src/test/data/JsonPropertyDirectoryStorageTest/invalidAndValidPropertyDirectory.json
  src/test/data/JsonPropertyDirectoryStorageTest/invalidPropertyDirectory.json
  src/test/data/JsonSerializablePropertyDirectoryTest/duplicatePropertyDirectory.json
  src/test/data/JsonSerializablePropertyDirectoryTest/invalidPropertyDirectory.json
  src/test/data/JsonSerializablePropertyDirectoryTest/typicalPropertyDirectory.json
  src/test/java/seedu/condonery/logic/LogicManagerTest.java
  src/test/java/seedu/condonery/logic/commands/CommandTestUtil.java
  src/test/java/seedu/condonery/logic/parser/property/AddPropertyCommandParserTest.java
  src/test/java/seedu/condonery/model/property/PropertyTest.java
  src/test/java/seedu/condonery/testutil/EditPropertyDescriptorBuilder.java
  src/test/java/seedu/condonery/testutil/PropertyBuilder.java
  src/test/java/seedu/condonery/testutil/PropertyUtil.java
  src/test/java/seedu/condonery/testutil/TypicalProperties.java
Labels: type.Story

#94 update DG for select command
  docs/DeveloperGuide.md
Labels: type.Task

#92 Add user uploaded client images
  src/main/java/seedu/condonery/logic/commands/client/AddClientCommand.java
  src/main/java/seedu/condonery/logic/commands/client/DeleteClientCommand.java
  src/main/java/seedu/condonery/logic/commands/client/EditClientCommand.java
  src/main/java/seedu/condonery/logic/parser/CondoneryParser.java
  src/main/java/seedu/condonery/logic/parser/client/AddClientCommandParser.java
  src/main/java/seedu/condonery/model/ModelManager.java
  src/main/java/seedu/condonery/model/UserPrefs.java
  src/main/java/seedu/condonery/model/client/Client.java
  src/main/java/seedu/condonery/model/client/ClientDirectory.java
  src/main/java/seedu/condonery/model/client/utils/ParseClientInterestedProperties.java
  src/main/java/seedu/condonery/storage/StorageManager.java
  src/main/java/seedu/condonery/ui/ClientCard.java
  src/main/java/seedu/condonery/ui/ClientListPanel.java
  src/main/java/seedu/condonery/ui/MainWindow.java
  src/main/resources/images/ClientDisplay.png
  src/main/resources/view/ClientListCard.fxml
  src/test/java/seedu/condonery/logic/commands/UndoCommandTest.java
  src/test/java/seedu/condonery/logic/commands/client/EditClientCommandTest.java
  src/test/java/seedu/condonery/logic/commands/property/EditPropertyCommandTest.java
Labels: type.Story, type.Enhancement

#195 add -p in UG and add -p in app requests for different arguments
  docs/UserGuide.md
Labels: severity.Low, type.Documentation

#193 Table of content on User Guide is broken, and does not show up
  docs/UserGuide.md
Labels: severity.VeryLow, type.Documentation

#196 Inconsistency in UG for select -c command
  docs/UserGuide.md
Labels: priority.Low, severity.VeryLow, type.Documentation

#197 Change file name output from shadowJar
  build.gradle
Labels: priority.Low

#198 Fix formatting error in AddPropertyCommand example
  src/main/java/seedu/condonery/logic/commands/property/AddPropertyCommand.java
Labels: priority.Low, Ready to Merge, type.Documentation

#199 Fix image in user guide
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/helpMessage.png
  src/main/resources/view/MainWindow.fxml
Labels: priority.Low, severity.Low, type.Documentation

#191 Unable to edit/change the status of properties
  src/main/java/seedu/condonery/logic/parser/property/EditPropertyCommandParser.java
Labels: type.Bug, severity.High
